baseURL = "https://m-c-frank.com/"
languageCode = "de-de"
title = "blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Martin Christoph Frank"
  description = "if you want to know something just ask"
  github = "m-c-frank"
  instagram = "mcfrank"
  email = "martinchristophfrank@gmail.com"
  url = "https://m-c-frank.com"
  keywords = "blog, technology"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  location = "Stadtbergen, Germany"
  userStatusEmoji = "🥋"
    
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
