name = "Github Style"
license = "MIT"
licenselink = "https://github.com/m-c-frank/github-style/blob/master/LICENSE"
description = "github-style hugo theme"
homepage = "https://m-c-frank.com"
tags = ["blog", "technology"]
min_version = "0.41"

[author]
  name = "Martin Christoph Frank"
  homepage = "https://m-c-frank.com"
